//! The router — every spine route, pre-registered by the lead.
//!
//! ⚠️ CONTRACT (wave githugr-spine-w1): agents do NOT edit this file. Handlers
//! are thin: provider → VM → screen render → page chrome. Unknown repo/intent
//! → 404.

use std::sync::Arc;

use axum::{
    Router,
    extract::{Path, State},
    http::{StatusCode, header},
    response::{IntoResponse, Redirect, Response},
    routing::get,
};
use maud::Markup;

use crate::layout::{self, Tab};
use crate::provider::Provider;
use crate::screens;

type Shared = Arc<dyn Provider>;

/// Build the app router over any [`Provider`].
pub fn app(provider: Shared) -> Router {
    Router::new()
        .route("/", get(root))
        .route("/static/kit.css", get(kit_css))
        .route("/r/{repo}", get(repo_home))
        .route("/r/{repo}/landing", get(landing))
        .route("/r/{repo}/intent/{id}", get(intent))
        .route("/r/{repo}/checks", get(checks))
        .route("/r/{repo}/insights", get(insights))
        .with_state(provider)
}

async fn root(State(p): State<Shared>) -> Redirect {
    Redirect::temporary(&format!("/r/{}/landing", p.default_repo()))
}

async fn kit_css() -> impl IntoResponse {
    (
        [(header::CONTENT_TYPE, "text/css; charset=utf-8")],
        include_str!("../static/kit.css"),
    )
}

fn not_found() -> Response {
    (StatusCode::NOT_FOUND, "404 — não existe por aqui").into_response()
}

fn ok(markup: Markup) -> Response {
    markup.into_response()
}

async fn repo_home(State(p): State<Shared>, Path(repo): Path<String>) -> Response {
    match p.repo_home(&repo) {
        Some(vm) => {
            let open = p.landing(&repo).map(|l| l.open_count);
            ok(layout::page(
                &repo,
                Tab::Code,
                &vm.repo,
                open,
                p.is_fixture(),
                screens::repo_home::SCREEN_CSS,
                screens::repo_home::render(&vm),
            ))
        }
        None => not_found(),
    }
}

async fn landing(State(p): State<Shared>, Path(repo): Path<String>) -> Response {
    match p.landing(&repo) {
        Some(vm) => ok(layout::page(
            &repo,
            Tab::Landing,
            "Landing (PRs)",
            Some(vm.open_count),
            p.is_fixture(),
            screens::landing::SCREEN_CSS,
            screens::landing::render(&vm),
        )),
        None => not_found(),
    }
}

async fn intent(State(p): State<Shared>, Path((repo, id)): Path<(String, String)>) -> Response {
    match p.intent(&repo, &id) {
        Some(vm) => {
            let open = p.landing(&repo).map(|l| l.open_count);
            ok(layout::page(
                &repo,
                Tab::Landing,
                &format!("intent {}", vm.id),
                open,
                p.is_fixture(),
                screens::intent::SCREEN_CSS,
                screens::intent::render(&vm),
            ))
        }
        None => not_found(),
    }
}

async fn checks(State(p): State<Shared>, Path(repo): Path<String>) -> Response {
    match p.checks(&repo) {
        Some(vm) => {
            let open = p.landing(&repo).map(|l| l.open_count);
            ok(layout::page(
                &repo,
                Tab::Checks,
                "Checks",
                open,
                p.is_fixture(),
                screens::checks::SCREEN_CSS,
                screens::checks::render(&vm),
            ))
        }
        None => not_found(),
    }
}

async fn insights(State(p): State<Shared>, Path(repo): Path<String>) -> Response {
    match p.insights(&repo) {
        Some(vm) => {
            let open = p.landing(&repo).map(|l| l.open_count);
            ok(layout::page(
                &repo,
                Tab::Insights,
                "Insights · Ledger",
                open,
                p.is_fixture(),
                screens::insights::SCREEN_CSS,
                screens::insights::render(&vm),
            ))
        }
        None => not_found(),
    }
}
