//! `hugit setup` — one-time global install of the git hooks via
//! `init.templateDir` (the "boot ceremony", no per-repo `hugit init`).
//!
//! Git has NO `post-init` hook, but it DOES copy the contents of
//! `init.templateDir` into every fresh `.git/` on `git init`. `setup` points
//! that global config at a hugit-owned template containing our 4 hooks
//! (post-commit / post-checkout / pre-push / post-merge) — so from then on,
//! EVERY `git init` on this machine ships the hugit hooks automatically.
//!
//! The hooks themselves LAZY-BOOT: on the first git op in a fresh repo they
//! create `.hugit/log.json` if it is absent (see the `[ -f "$LOG" ]` block in
//! `init::hook_script`), so a repo that never ran `hugit init` still becomes
//! active the moment someone commits/checks out.
//!
//! `setup` never touches a repo's hooks directly (that stays `hugit init`'s
//! job); it only writes ONE global config key + a template directory the user
//! owns. Idempotent: re-running rewrites the same template + config.

use std::path::PathBuf;
use std::process::ExitCode;

use serde_json::{Value, json};

use super::init;

/// The 4 git hooks (+ the capture kinds they fire).
const HOOK_KINDS: [&str; 4] = ["post-commit", "post-checkout", "pre-push", "post-merge"];

/// `hugit setup` args.
#[derive(clap::Args, Debug)]
pub struct SetupArgs {
    /// Optional explicit template dir to install instead of the default
    /// `~/.config/hugit/template` (for tests / custom layouts).
    #[arg(long)]
    pub dir: Option<PathBuf>,
}

/// Run `hugit setup`.
pub fn run(args: SetupArgs) -> ExitCode {
    match do_setup(&args) {
        Ok(v) => {
            println!("{v}");
            ExitCode::SUCCESS
        }
        Err(e) => {
            println!("{}", e.to_json());
            e.exit_code()
        }
    }
}

fn do_setup(args: &SetupArgs) -> Result<Value, crate::porcelain::PorcelainError> {
    let template_dir = args.dir.clone().unwrap_or_else(default_template_dir);
    let hooks_dir = template_dir.join("hooks");
    std::fs::create_dir_all(&hooks_dir)
        .map_err(|e| crate::porcelain::PorcelainError::io("create template dir", &hooks_dir, &e))?;

    for kind in HOOK_KINDS {
        let script = init::hook_script(kind);
        let dest = hooks_dir.join(kind);
        std::fs::write(&dest, script)
            .map_err(|e| crate::porcelain::PorcelainError::io("write template hook", &dest, &e))?;
        // Hooks must be executable for git to run them from a template.
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let _ = std::fs::set_permissions(&dest, std::fs::Permissions::from_mode(0o755));
        }
    }
    // Mark ownership so an operator can tell the template apart and, if ever
    // needed, uninstall it cleanly.
    std::fs::write(
        template_dir.join("OWNED-BY-HUGIT"),
        b"Generated by `hugit setup`; safe to delete. Points git's global init.templateDir at this dir.\n",
    )
    .map_err(|e| {
        crate::porcelain::PorcelainError::io("write template marker", &template_dir, &e)
    })?;

    // Point git's GLOBAL init.templateDir at it (idempotent overwrite).
    let git_out = std::process::Command::new("git")
        .args([
            "config",
            "--global",
            "init.templateDir",
            template_dir.to_str().unwrap_or(""),
        ])
        .output()
        .map_err(|e| crate::porcelain::PorcelainError::io("run git config", &template_dir, &e))?;
    if !git_out.status.success() {
        return Err(crate::porcelain::PorcelainError::new(
            "git_config_failed",
            "`git config --global init.templateDir` failed",
            "is git on PATH and is a repo not required for global config?",
        ));
    }

    Ok(json!({
        "template_dir": template_dir.display().to_string(),
        "hooks": HOOK_KINDS,
        "global_init_template_dir": true,
        "next": "any future `git init` in this machine already ships the hugit hooks; existing repos use `hugit init <dir>` or a first git op lazy-boots them.",
    }))
}

/// Default template dir under the user's config root.
fn default_template_dir() -> PathBuf {
    dirs_home_config("hugit").join("template")
}

/// `$XDG_CONFIG_HOME/hugit` else `~/.config/hugit`.
fn dirs_home_config(leaf: &str) -> PathBuf {
    if let Some(xdg) = std::env::var_os("XDG_CONFIG_HOME") {
        PathBuf::from(xdg).join(leaf)
    } else {
        let home = std::env::var_os("HOME").unwrap_or_else(|| "/tmp".into());
        PathBuf::from(home).join(".config").join(leaf)
    }
}
