//! App smoke — the scaffold's standing oracle: every spine route serves over
//! the fixture world; unknown repo/intent 404s; `/` redirects into the world.
//! Agents do not edit this file; screen WPs add their own `tests/screen_*.rs`.

use std::sync::Arc;

use axum::body::Body;
use axum::http::{Request, StatusCode};
use http_body_util::BodyExt;
use hugit_web::fixture::FixtureProvider;
use tower::ServiceExt;

fn app() -> axum::Router {
    hugit_web::app(Arc::new(FixtureProvider::seed()))
}

async fn get(path: &str) -> (StatusCode, String) {
    let resp = app()
        .oneshot(Request::builder().uri(path).body(Body::empty()).unwrap())
        .await
        .unwrap();
    let status = resp.status();
    let bytes = resp.into_body().collect().await.unwrap().to_bytes();
    (status, String::from_utf8_lossy(&bytes).into_owned())
}

#[tokio::test]
async fn root_redirects_into_the_default_repo() {
    let resp = app()
        .oneshot(Request::builder().uri("/").body(Body::empty()).unwrap())
        .await
        .unwrap();
    assert_eq!(resp.status(), StatusCode::TEMPORARY_REDIRECT);
    let loc = resp.headers().get("location").unwrap().to_str().unwrap();
    assert_eq!(loc, "/r/hugit/landing");
}

#[tokio::test]
async fn every_spine_route_serves() {
    for path in [
        "/r/hugit",
        "/r/hugit/landing",
        "/r/hugit/intent/intent-pr-0",
        "/r/hugit/checks",
        "/r/hugit/insights",
    ] {
        let (status, body) = get(path).await;
        assert_eq!(status, StatusCode::OK, "route {path} must serve");
        assert!(
            body.contains("githugr"),
            "route {path} must render the chrome"
        );
        assert!(
            body.contains("fixture"),
            "route {path} must carry the honest fixture badge"
        );
    }
}

#[tokio::test]
async fn kit_css_is_served() {
    let (status, body) = get("/static/kit.css").await;
    assert_eq!(status, StatusCode::OK);
    assert!(body.contains("--bg:#101013"), "Linear Noir tokens present");
}

#[tokio::test]
async fn unknown_repo_and_intent_404() {
    for path in [
        "/r/nope",
        "/r/nope/landing",
        "/r/hugit/intent/no-such-intent",
        "/r/nope/checks",
        "/r/nope/insights",
    ] {
        let (status, _) = get(path).await;
        assert_eq!(status, StatusCode::NOT_FOUND, "route {path} must 404");
    }
}

#[tokio::test]
async fn tabs_navigate_to_real_routes() {
    let (_, body) = get("/r/hugit/landing").await;
    for href in [
        "href=\"/r/hugit\"",
        "href=\"/r/hugit/landing\"",
        "href=\"/r/hugit/checks\"",
        "href=\"/r/hugit/insights\"",
    ] {
        assert!(body.contains(href), "tabbar must link {href}");
    }
}
