#!/usr/bin/env bash
# WP-C4 acceptance suite — hugit-checks regen driver (items ①②③④⑤⑥).
# Contract: docs/plan/wp-contracts/WP-C4.md.
# Owned items:
#   ① lockfile union regen green, 0 markers
#   ② deterministic regen
#   ③ non-lockfile untouched
#   ④ all three derived classes exercised: codegen + snapshot files regenerate (never text-merge);
#      hand-edits to derived files discarded+regenerated
#   ⑤ regeneration FAILURE → fail CLOSED with clear status; never silently/partially merged
#   ⑥ METHOD proof: fixture where clean text-merge yields DIFFERENT bytes than regeneration →
#      regenerated bytes win AND merge codepath provably never entered for derived-classified paths
# Oracle: crates/hugit-checks/tests/acceptance_wp-c4.rs with item_1..item_6 tests.
# RED on absent crate; structural checks are direct bash assertions.

SUITE_ID="wp-c4"
export SUITE_ID
source "$(dirname "$0")/../lib.sh"

CRATE=crates/hugit-checks
ACCEPTANCE_RS="$CRATE/tests/acceptance_wp-c4.rs"
WP_ID="wp-c4"

# ── (a) claimed crate exists ─────────────────────────────────────────────────
check "① crate hugit-checks present (Cargo.toml)" \
  test -f "$CRATE/Cargo.toml"
check "① crate hugit-checks present (src/lib.rs)" \
  test -f "$CRATE/src/lib.rs"

# ── (a) regen/driver/ dir exists (Claims boundary) ───────────────────────────
check "① regen/driver/ dir exists: $CRATE/src/regen/driver/" \
  test -d "$CRATE/src/regen/driver"

# ── (a) acceptance test file committed ───────────────────────────────────────
check "① acceptance file committed: $ACCEPTANCE_RS" \
  test -f "$ACCEPTANCE_RS"

# ── (b) cargo test --list declares item_1..item_6 ────────────────────────────
TESTLIST="$(cargo test -p hugit-checks --test "acceptance_${WP_ID}" -- --list 2>/dev/null || true)"

check "① item_1 test declared (lockfile_union_regen_green_zero_markers)" \
  bash -c "echo '$TESTLIST' | grep -q 'item_1'"
check "② item_2 test declared (deterministic_regen)" \
  bash -c "echo '$TESTLIST' | grep -q 'item_2'"
check "③ item_3 test declared (non_lockfile_untouched)" \
  bash -c "echo '$TESTLIST' | grep -q 'item_3'"
check "④ item_4 test declared (three_derived_classes_exercised)" \
  bash -c "echo '$TESTLIST' | grep -q 'item_4'"
check "⑤ item_5 test declared (regen_failure_fail_closed)" \
  bash -c "echo '$TESTLIST' | grep -q 'item_5'"
check "⑥ item_6 test declared (method_proof_merge_path_never_entered)" \
  bash -c "echo '$TESTLIST' | grep -q 'item_6'"

# ── (c) cargo test -p hugit-checks --test acceptance_wp-c4 green ─────────────
check "①…⑥ cargo test -p hugit-checks --test acceptance_wp-c4 green" \
  cargo test -p hugit-checks --test "acceptance_${WP_ID}"

# ── (d) structural: no writes outside regen/driver/ (Claims disjointness) ────
check "③ regen/gate/ not present in hugit-checks/src (D12 boundary respected)" \
  bash -c "! test -d '$CRATE/src/regen/gate'"

# ── (d) structural: Cargo.lock + pnpm-lock drivers present (impl notes v0) ───
check "① Cargo.lock driver src file present" \
  bash -c "find '$CRATE/src/regen/driver' -name '*cargo*' | grep -q ."
check "① pnpm-lock driver src file present" \
  bash -c "find '$CRATE/src/regen/driver' -name '*pnpm*' | grep -q ."

# ── (d) structural: fail-closed marker present in regen driver src ────────────
check "⑤ fail-closed error/status variant referenced in regen/driver src" \
  bash -c "grep -rEq 'FailClosed|fail_closed|RegenFailed|regen_failed' '$CRATE/src/regen/driver/'"

# ── (d) structural: ⑥ fixture committed (text-merge != regen proof) ──────────
check "⑥ method-proof fixture committed under $CRATE/tests/fixtures/" \
  bash -c "find '$CRATE/tests/fixtures' -name '*method_proof*' -o -name '*merge_vs_regen*' 2>/dev/null | grep -q ."

finish
