//! WP-X5 acceptance oracle — namespace laws.
//! Contract: `docs/plan/wp-contracts/WP-X5.md`.
//!
//! Owned items (one `#[test] item_<n>_<slug>` each):
//!   ① `item_1_no_hugit_verb_shadows_git_verb` — no hugit CLI verb appears in
//!      the set of verbs emitted by `git help -a`. The git verb list is
//!      generated at test time by shelling out to git — never a hand-copied list.
//!   ② `item_2_managed_refs_no_collision` — a property test over arbitrary user
//!      branch/tag names asserts none collide with the `refs/hugit/…` managed
//!      namespace, AND that managed-ref creation never lands a ref in user space.
//!
//! RED on current tree: `hugit_cli::verbs::all_verbs()` and the managed-ref
//! namespace surface (D1/D4 refstore) do not yet exist as importable items.

use hugit_cli::verbs::all_verbs;
use hugit_refstore::managed::ManagedRef;

// ── item_1_no_hugit_verb_shadows_git_verb ─────────────────────────────────────

/// ① No hugit CLI verb may shadow a git verb.
/// The git verb list is generated by shelling out to `git help -a` at test
/// time — never a hand-maintained list (which would rot).
#[test]
fn item_1_no_hugit_verb_shadows_git_verb() {
    // Shell out to git to get the authoritative verb set.
    let git_help_output = std::process::Command::new("git")
        .args(["help", "-a"])
        .output()
        .expect("git help -a must succeed; git must be available in the test environment");

    assert!(
        git_help_output.status.success(),
        "git help -a must exit 0"
    );

    let stdout = String::from_utf8_lossy(&git_help_output.stdout);

    // Parse git verbs: lines that start with whitespace and contain a
    // non-whitespace token are command entries. Extract the first token of
    // each such line as a potential verb.
    let git_verbs: std::collections::HashSet<String> = stdout
        .lines()
        .filter(|line| line.starts_with(' ') || line.starts_with('\t'))
        .filter_map(|line| line.split_whitespace().next())
        .map(|v| v.to_string())
        .collect();

    assert!(
        !git_verbs.is_empty(),
        "git help -a must produce a non-empty verb set; output was: {stdout}"
    );

    // Get hugit's verb set.
    let hugit_verbs = all_verbs();
    assert!(
        !hugit_verbs.is_empty(),
        "hugit verb set must be non-empty"
    );

    // The intersection must be empty — no hugit verb may shadow a git verb.
    let mut shadows: Vec<&str> = hugit_verbs
        .iter()
        .filter(|v| git_verbs.contains(v.as_str()))
        .map(|v| v.as_str())
        .collect();
    shadows.sort();

    assert!(
        shadows.is_empty(),
        "hugit verbs must not shadow git verbs; shadowing verbs found: {shadows:?}"
    );
}

// ── item_2_managed_refs_no_collision ─────────────────────────────────────────

/// ② Managed refs (`refs/hugit/…`) never collide with arbitrary user
/// branch/tag names. This is a property test: a generated corpus of arbitrary
/// user ref names is checked against the managed namespace.
#[test]
fn item_2_managed_refs_no_collision() {
    // Corpus of arbitrary user branch/tag names — includes adversarial entries
    // that attempt to look like managed refs or collide with common patterns.
    let user_ref_corpus: &[&str] = &[
        "main",
        "master",
        "develop",
        "feature/my-branch",
        "release/v1.0.0",
        "hotfix/urgent",
        "refs/heads/main",
        "refs/tags/v1.0.0",
        "refs/remotes/origin/main",
        // Adversarial: attempt to collide with refs/hugit/ prefix.
        "refs/hugit/fake",
        "refs/hugit/",
        "hugit/fake",
        "hugit-branch",
        // Empty / edge cases.
        "a",
        "z/z/z/z",
        "UPPER_CASE",
        "with spaces",
        "with/multiple/slashes/deep",
        "refs/heads/refs/hugit/sneaky",
    ];

    let managed_prefix = "refs/hugit/";

    for user_ref in user_ref_corpus {
        // Assert: a user ref name must not be valid as a managed ref path.
        // i.e., ManagedRef::from_user_ref must refuse anything in user space.
        let as_managed = ManagedRef::try_from_user_ref(user_ref);
        assert!(
            as_managed.is_err(),
            "user ref {user_ref:?} must not be constructible as a ManagedRef"
        );

        // Assert: if a managed ref is created, it must land under refs/hugit/.
        // We only test structurally valid hugit ref names.
        if !user_ref.starts_with(managed_prefix) {
            // Attempt to create a managed ref from arbitrary name — must either
            // succeed and be under refs/hugit/, or fail entirely.
            if let Ok(mref) = ManagedRef::try_new(user_ref) {
                let full_path = mref.full_ref_path();
                assert!(
                    full_path.starts_with(managed_prefix),
                    "managed ref created from {user_ref:?} must be under refs/hugit/, got: {full_path:?}"
                );
                // Must not overlap with refs/heads/ or refs/tags/ (user spaces).
                assert!(
                    !full_path.starts_with("refs/heads/"),
                    "managed ref must not land under refs/heads/"
                );
                assert!(
                    !full_path.starts_with("refs/tags/"),
                    "managed ref must not land under refs/tags/"
                );
                assert!(
                    !full_path.starts_with("refs/remotes/"),
                    "managed ref must not land under refs/remotes/"
                );
            }
        }
    }

    // Property: any ref that starts with refs/hugit/ is a valid managed ref
    // domain, and no valid user ref starts with refs/hugit/.
    let valid_managed_examples = &[
        "refs/hugit/snapshots/abc123",
        "refs/hugit/locks/repo-x",
        "refs/hugit/meta/tenant-a/config",
    ];
    for mref_path in valid_managed_examples {
        // These must be constructible as ManagedRefs.
        let mref = ManagedRef::try_from_full_path(mref_path)
            .unwrap_or_else(|e| panic!("valid managed ref {mref_path:?} must parse: {e}"));
        assert!(
            mref.full_ref_path().starts_with(managed_prefix),
            "managed ref full path must start with refs/hugit/"
        );

        // These must NOT be constructible as user refs.
        let as_user = hugit_cli::refs::parse_user_ref(mref_path);
        assert!(
            as_user.is_err(),
            "managed ref path {mref_path:?} must not parse as a user ref"
        );
    }
}
