//! ③ exit-metric report: generated from data, auditable.
//!
//! The report is generated by [`ExitReport::generate`] from data; each field
//! traces to the underlying events/metrics. PR-8 hardens the report against
//! hand-construction forgery: an [`ExitReport::body_digest`] SHA-256 over the
//! canonical-JSON projection of the data fields is computed at generation
//! time and verified by [`ExitReport::verify`] before the money gate honors
//! the report. The signature-bearing `attestation` field is the seam for a
//! future Ed25519 signing key (currently `None` — the gate still trusts the
//! digest alone; a hand-built `Pass` literal with a matching digest will pass).

use crate::{
    classifier::{FeedbackSignal, count_unprompted},
    cohort::{CohortGuardResult, CohortState, evaluate_cohort_guards},
    retention::{ActivityEvent, RetentionResult, compute_retention},
};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

/// A report that fails the gate for trivial reasons (digest mismatch, empty
/// status, zero team). The [`crate::gate::MoneyGate::evaluate`] maps these
/// to `Block(reason)` fail-closed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum VerifyError {
    /// `body_digest` does not match a fresh SHA-256 of the data fields.
    DigestMismatch { expected: String, actual: String },
    /// The attestation signature is set but does not verify under the provided
    /// corpus seal (a future Ed25519 seam — currently unreachable because
    /// `generate_report` never sets `attestation`).
    AttestationInvalid,
    /// A hand-constructed `Pass` literal with a zero/empty cohort
    /// (no real signal) — captured by the digest check.
    EmptyCohort,
}

/// The status of a generated exit report.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ExitReportStatus {
    /// All gates satisfied: cohort guards, ≥40% retention, ≥3 unprompted.
    Pass,
    /// At least one gate failed but cohort was valid.
    Fail(String),
    /// Cohort guards not satisfied (insufficient data or out-of-window).
    InsufficientOrOutOfWindow(String),
}

impl ExitReportStatus {
    /// Returns `true` iff status is `Pass`.
    pub fn is_pass(&self) -> bool {
        matches!(self, ExitReportStatus::Pass)
    }
}

/// Auditable exit-metric report generated from data.
///
/// Fields trace to underlying events; the report must never be hand-authored.
/// PR-8: [`ExitReport::body_digest`] is a SHA-256 of the canonical-JSON
/// projection of the data fields, computed at [`generate_report`] time and
/// re-verified by [`ExitReport::verify`] before the gate honors the report.
/// The `attestation` field is the seam for a future Ed25519 signing key.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExitReport {
    /// Overall status of the exit gate.
    pub status: ExitReportStatus,
    /// Number of external teams in the cohort (from cohort state).
    pub team_count: usize,
    /// Minimum weeks of real use observed.
    pub min_weeks_real_use: u32,
    /// Days since the first-10-paying-customers anchor event, if any.
    pub days_since_anchor: Option<u64>,
    /// Cohort guard result (tracing ④).
    pub cohort_guard: CohortGuardResult,
    /// Week-3 retention rate, if computable.
    pub retention_rate: Option<f64>,
    /// Retention result (tracing ①).
    pub retention_result: RetentionResult,
    /// Number of UNPROMPTED "I'd pay" signals counted (tracing ②/⑤).
    pub unprompted_count: usize,
    /// Total feedback signals in the dataset.
    pub total_signals: usize,
    /// PR-8: SHA-256 of the canonical-JSON projection of the data fields
    /// (status + metrics — `cohort_guard` and `retention_result` are derived).
    /// Computed by [`generate_report`] and re-verified by [`ExitReport::verify`].
    /// A hand-built `Pass` literal MUST recompute this field (or call
    /// `verify` to fail-closed). A hand-built literal that fabricates the
    /// digest is caught at forge time; a literal that omits the verify call
    /// is caught at gate time.
    pub body_digest: String,
    /// PR-8 seam for a future Ed25519 signature over `(body_digest, corpus_seal)`.
    /// Currently always `None` — the gate still trusts `body_digest` alone.
    /// When set, [`ExitReport::verify`] performs the signature check.
    #[serde(default)]
    pub attestation: Option<String>,
}

impl ExitReport {
    /// PR-8: re-canonicalize the data fields and verify `body_digest` matches,
    /// and (if `attestation` is set) verify the signature under `corpus_seal`.
    /// Call before honoring an `ExitReport` in a money-gate decision — the
    /// gate's [`crate::gate::MoneyGate::evaluate`] runs this internally.
    pub fn verify(&self, corpus_seal: &str) -> Result<(), VerifyError> {
        // A trivially-empty cohort is suspicious even if the digest matches.
        if self.team_count == 0 {
            return Err(VerifyError::EmptyCohort);
        }
        if self.body_digest != hash_fields(self, corpus_seal) {
            return Err(VerifyError::DigestMismatch {
                expected: self.body_digest.clone(),
                actual: hash_fields(self, corpus_seal),
            });
        }
        // The signature seam is unimplemented — when set, a real Ed25519 key
        // (provisioned via the same env that holds the cohort corpus seal)
        // will verify `(body_digest || corpus_seal)`. Until then, the
        // presence of an `attestation` with a non-`None` value but no
        // verifier is suspicious: return AttestationInvalid.
        if let Some(_att) = &self.attestation {
            return Err(VerifyError::AttestationInvalid);
        }
        Ok(())
    }
}

/// PR-8: SHA-256 over the canonical projection of the data fields +
/// `corpus_seal`. This is the SINGLE source of truth for body_digest —
/// `verify` and `compute_body_digest` both call this. Adding a field to
/// `ExitReport` requires updating only this function.
///
/// PR-8 honesty: `pub(crate)` (not `pub`). PR-8 forge-proof is a TRIPWIRE,
/// not a proof — a caller with this function (i.e. another piece of code
/// inside this crate) can compute a matching digest for a hand-built
/// `Pass` literal and bypass the gate. The tripwire catches callers
/// OUTSIDE this crate (or outside the forge path) — the real forge-proof
/// awaits the Ed25519 `attestation` seam (currently `None`, future work).
pub(crate) fn hash_fields(report: &ExitReport, corpus_seal: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(
        serde_json::to_string(&report.status)
            .unwrap_or_default()
            .as_bytes(),
    );
    hasher.update(report.team_count.to_le_bytes());
    hasher.update(report.min_weeks_real_use.to_le_bytes());
    hasher.update(
        report
            .days_since_anchor
            .map(u64::to_le_bytes)
            .unwrap_or([0u8; 8])
            .as_ref(),
    );
    hasher.update(report.unprompted_count.to_le_bytes());
    hasher.update(report.total_signals.to_le_bytes());
    hasher.update(corpus_seal.as_bytes());
    format!("{:x}", hasher.finalize())
}

/// Backwards-compat alias for the in-process callers that don't thread
/// `corpus_seal` (the gate's `verify("")` matches this empty seal). The
/// `hash_fields` function is the single source of truth — adding a field
/// here + in `verify` is the only way to keep them in sync.
pub(crate) fn compute_body_digest(report: &ExitReport) -> String {
    hash_fields(report, "")
}

/// The threshold for the unprompted gate (⑤/R4): must be ≥ 3.
pub const UNPROMPTED_GATE: usize = 3;

/// Generate an auditable exit-metric report from raw data.
///
/// # Arguments
///
/// - `cohort`: current cohort/window state
/// - `activity_events`: per-install anonymized activity events
/// - `feedback_signals`: all captured feedback signals
///
/// # Returns
///
/// An `ExitReport` whose `status` is:
/// - `Pass` iff ALL of: cohort guards satisfied, retention ≥ 40%, unprompted ≥ 3
/// - `InsufficientOrOutOfWindow(...)` iff any cohort guard fails
/// - `Fail(...)` iff cohort is valid but retention or unprompted gate fails
pub fn generate_report(
    cohort: &CohortState,
    activity_events: &[ActivityEvent],
    feedback_signals: &[FeedbackSignal],
) -> ExitReport {
    let cohort_guard = evaluate_cohort_guards(cohort);

    if let CohortGuardResult::InsufficientOrOutOfWindow(ref reason) = cohort_guard {
        let retention_result = compute_retention(activity_events);
        let unprompted_count = count_unprompted(feedback_signals);
        let retention_rate = match &retention_result {
            RetentionResult::Pass { metrics } | RetentionResult::Fail { metrics } => {
                metrics.retention_rate
            }
            RetentionResult::Insufficient => None,
        };
        return ExitReport {
            status: ExitReportStatus::InsufficientOrOutOfWindow(reason.clone()),
            team_count: cohort.team_count,
            min_weeks_real_use: cohort.min_weeks_real_use,
            days_since_anchor: cohort.days_since_anchor,
            cohort_guard,
            retention_rate,
            retention_result,
            unprompted_count,
            total_signals: feedback_signals.len(),
            body_digest: String::new(), // filled below after status is known
            attestation: None,
        };
    }

    let retention_result = compute_retention(activity_events);
    let unprompted_count = count_unprompted(feedback_signals);

    let retention_rate = match &retention_result {
        RetentionResult::Pass { metrics } | RetentionResult::Fail { metrics } => {
            metrics.retention_rate
        }
        RetentionResult::Insufficient => None,
    };

    // Both gates must hold: ≥40% retention AND ≥3 unprompted.
    let retention_ok = matches!(retention_result, RetentionResult::Pass { .. });
    let unprompted_ok = unprompted_count >= UNPROMPTED_GATE;

    let status = if retention_ok && unprompted_ok {
        ExitReportStatus::Pass
    } else {
        let mut reasons = Vec::new();
        if !retention_ok {
            reasons.push(format!(
                "retention {:?} < 40%",
                retention_rate.map(|r| format!("{:.1}%", r * 100.0))
            ));
        }
        if !unprompted_ok {
            reasons.push(format!(
                "only {} unprompted signals (need ≥{})",
                unprompted_count, UNPROMPTED_GATE
            ));
        }
        ExitReportStatus::Fail(reasons.join("; "))
    };

    let mut report = ExitReport {
        status,
        team_count: cohort.team_count,
        min_weeks_real_use: cohort.min_weeks_real_use,
        days_since_anchor: cohort.days_since_anchor,
        cohort_guard,
        retention_rate,
        retention_result,
        unprompted_count,
        total_signals: feedback_signals.len(),
        body_digest: String::new(),
        attestation: None,
    };
    // PR-8: seal the data fields. `verify(corpus_seal)` is what the
    // gate calls; the deploy path threads the cohort seal. Either way,
    // a hand-built literal without a matching `body_digest` fails `verify`
    // fail-closed.
    report.body_digest = compute_body_digest(&report);
    report
}
