//! ③ exit-metric report: generated from data, auditable.
//!
//! The report is never hand-written; it is generated by `generate_report`.
//! Each field traces to the underlying events/metrics.

use crate::{
    classifier::{FeedbackSignal, count_unprompted},
    cohort::{CohortGuardResult, CohortState, evaluate_cohort_guards},
    retention::{ActivityEvent, RetentionResult, compute_retention},
};
use serde::{Deserialize, Serialize};

/// The status of a generated exit report.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ExitReportStatus {
    /// All gates satisfied: cohort guards, ≥40% retention, ≥3 unprompted.
    Pass,
    /// At least one gate failed but cohort was valid.
    Fail(String),
    /// Cohort guards not satisfied (insufficient data or out-of-window).
    InsufficientOrOutOfWindow(String),
}

impl ExitReportStatus {
    /// Returns `true` iff status is `Pass`.
    pub fn is_pass(&self) -> bool {
        matches!(self, ExitReportStatus::Pass)
    }
}

/// Auditable exit-metric report generated from data.
///
/// Fields trace to underlying events; the report must never be hand-authored.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExitReport {
    /// Overall status of the exit gate.
    pub status: ExitReportStatus,
    /// Number of external teams in the cohort (from cohort state).
    pub team_count: usize,
    /// Minimum weeks of real use observed.
    pub min_weeks_real_use: u32,
    /// Days since the first-10-paying-customers anchor event, if any.
    pub days_since_anchor: Option<u64>,
    /// Cohort guard result (tracing ④).
    pub cohort_guard: CohortGuardResult,
    /// Week-3 retention rate, if computable.
    pub retention_rate: Option<f64>,
    /// Retention result (tracing ①).
    pub retention_result: RetentionResult,
    /// Number of UNPROMPTED "I'd pay" signals counted (tracing ②/⑤).
    pub unprompted_count: usize,
    /// Total feedback signals in the dataset.
    pub total_signals: usize,
}

/// The threshold for the unprompted gate (⑤/R4): must be ≥ 3.
pub const UNPROMPTED_GATE: usize = 3;

/// Generate an auditable exit-metric report from raw data.
///
/// # Arguments
///
/// - `cohort`: current cohort/window state
/// - `activity_events`: per-install anonymized activity events
/// - `feedback_signals`: all captured feedback signals
///
/// # Returns
///
/// An `ExitReport` whose `status` is:
/// - `Pass` iff ALL of: cohort guards satisfied, retention ≥ 40%, unprompted ≥ 3
/// - `InsufficientOrOutOfWindow(...)` iff any cohort guard fails
/// - `Fail(...)` iff cohort is valid but retention or unprompted gate fails
pub fn generate_report(
    cohort: &CohortState,
    activity_events: &[ActivityEvent],
    feedback_signals: &[FeedbackSignal],
) -> ExitReport {
    let cohort_guard = evaluate_cohort_guards(cohort);

    if let CohortGuardResult::InsufficientOrOutOfWindow(ref reason) = cohort_guard {
        let retention_result = compute_retention(activity_events);
        let unprompted_count = count_unprompted(feedback_signals);
        let retention_rate = match &retention_result {
            RetentionResult::Pass { metrics } | RetentionResult::Fail { metrics } => {
                metrics.retention_rate
            }
            RetentionResult::Insufficient => None,
        };
        return ExitReport {
            status: ExitReportStatus::InsufficientOrOutOfWindow(reason.clone()),
            team_count: cohort.team_count,
            min_weeks_real_use: cohort.min_weeks_real_use,
            days_since_anchor: cohort.days_since_anchor,
            cohort_guard,
            retention_rate,
            retention_result,
            unprompted_count,
            total_signals: feedback_signals.len(),
        };
    }

    let retention_result = compute_retention(activity_events);
    let unprompted_count = count_unprompted(feedback_signals);

    let retention_rate = match &retention_result {
        RetentionResult::Pass { metrics } | RetentionResult::Fail { metrics } => {
            metrics.retention_rate
        }
        RetentionResult::Insufficient => None,
    };

    // Both gates must hold: ≥40% retention AND ≥3 unprompted.
    let retention_ok = matches!(retention_result, RetentionResult::Pass { .. });
    let unprompted_ok = unprompted_count >= UNPROMPTED_GATE;

    let status = if retention_ok && unprompted_ok {
        ExitReportStatus::Pass
    } else {
        let mut reasons = Vec::new();
        if !retention_ok {
            reasons.push(format!(
                "retention {:?} < 40%",
                retention_rate.map(|r| format!("{:.1}%", r * 100.0))
            ));
        }
        if !unprompted_ok {
            reasons.push(format!(
                "only {} unprompted signals (need ≥{})",
                unprompted_count, UNPROMPTED_GATE
            ));
        }
        ExitReportStatus::Fail(reasons.join("; "))
    };

    ExitReport {
        status,
        team_count: cohort.team_count,
        min_weeks_real_use: cohort.min_weeks_real_use,
        days_since_anchor: cohort.days_since_anchor,
        cohort_guard,
        retention_rate,
        retention_result,
        unprompted_count,
        total_signals: feedback_signals.len(),
    }
}
